name: Lint PR Title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
      - name: Validate Semantic PR Title
        uses: actions/setup-go@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
